#!/usr/bin/env bash

log() {
  echo -e '\033[38;5;46m[system]\033[39m' $@
}

# check docker is running
container_name=$(docker compose ps -q)
if [ "$(docker container inspect -f '{{.State.Running}}' ${container_name} 2>/dev/null)" = "true" ]; then
  log 'docker is running'
else
  log 'starting docker'
  docker compose up -d
  sleep 1
fi

log 'starting server'
node server.js 2>/dev/null &
log 'starting client'
node client.js &
sleep 0.5

log 'telling server to send message'
curl http://localhost:4321/message
log 'telling server to send message to user'
curl http://localhost:4321/user

log 'shutting down'
jobs
kill %1
kill %2
